### ISSUE TITLE
reduce implementation fails when the operand is an array of variables

### ISSUE THREAD

**Issue by stapelberg** [QubitProducts/jsonlogic#1]
Thanks for publishing your jsonlogic package!

The following is an existing, passing test case, where the reduce operand is a variable that expands to an array:
```json
    [
        {"reduce": [
            {"var":"desserts"},
            {"+":[ {"var":"accumulator"}, {"var":"current.qty"}]},
            0
        ]},
        {"desserts":[
            {"name":"apple","qty":1},
            {"name":"brownie","qty":2},
            {"name":"cupcake","qty":3}
        ]},
        6
    ],
```

When changing that test case to use an array operand of individual variables, the test unexpectedly fails:
```json
    [
        {"reduce": [
            [
		{"var":"desserts.apple"},
		{"var":"desserts.brownie"},
		{"var":"desserts.cupcake"}
	    ],
            {"+":[ {"var":"accumulator"}, {"var":"current.qty"}]},
            0
        ]},
        {"desserts":{
           "apple":{"qty":1},
            "brownie":{"qty":2},
            "cupcake":{"qty":3}
        }},
        6
    ],
```

This is unfortunate because the COVID certificate business rules use the latter form, see e.g. https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/blob/aad2a0fa28ac53e4bf2db3b21ad08f453db5abb8/NL/GR-NL-0000/rule.json#L27

As far as I can tell, the code which dereferences `current.qty` does not expand variables.

I’m not 100% sure how to best fix this. Any ideas?

Thank you

**Comment by stapelberg** [comment]
cc @tcolgate (just in case you’re not subscribed to this repo, I see 0 watchers)

**Comment by tcolgate** [comment]
Cheers for the CC, this repo got moved and I forgot to rewatch. I need to review the problem case. Have you tested the behaviour on the JS implementation (I take that as canon).

**Comment by stapelberg** [comment]
If the https://jsonlogic.com/play.html uses the javascript implementation under the hood (I’d hope so!), then yes, the canonical implementation evaluates this expression + data to 6, whereas the Go jsonlogic package incorrectly evaluates it to 0:
![jslogic](https://user-images.githubusercontent.com/55506/127703940-8fde75d1-0675-4c95-8f0c-1b9c1419348b.jpg)

**Comment by tcolgate** [comment]
Cool, good enough for me. I'll add a test case and go from there.

**Comment by tcolgate** [comment]
This is more complicated than I expected. Because the first arg isn't a jsonlogic clause (it's just an array), we don't treat it as one, so don't build an arg function and just pass in the raw array. It's essentially breaking at the unmarshaling stage. This simpler case also fails when compared to
the playground.
`{"+":[[{"var": "arg"}],2]}`

**Comment by stapelberg** [comment]
This matches my understanding :) What would be the best way to fix this?

**Comment by tcolgate** [comment]
Not 100% sure yet. I think buildNullOp needs to treat any array as a bunch of term args. But the parser also needs to attempt to unmarshal individual arguments as a Clause or []Cluase (currently it only does the latter), and then wrap the response in a nullOp. Not exactly sure on the details yet.

**Comment by tcolgate** [comment]
Ok, so, I thin the correct behaviour is to treat 
```
[1,2,3,{"var": "hello},...]]
```
or any naked array where a clause could be, as a noop over that array as args, internally that would be
````
{"",[]args here]}
````
I nearly have it working

**Comment by tcolgate** [comment]
Can you test the branch. Your example now works, along with the simpler cases of arrays containing clauses (which also seem to be supported in the original implementation)

**Comment by stapelberg** [comment]
> Can you test the branch. Your example now works, along with the simpler cases of arrays containing clauses (which also seem to be supported in the original implementation)

Thank you for the quick fix!

I can confirm that with the `nakedarray` branch, all the covid-19 rules test cases I currently have implemented newly pass 🎉

**Comment by tcolgate** [comment]
I've pushed the marshaling change. Unfortunately the change seems to result in a fairly serious performance regression. I'll need a bit of time to debug this and see if we can get rid of it.
```
benchmark               old ns/op     new ns/op     delta
BenchmarkFizzBuzz-4     531           533           +0.30%
BenchmarkIn-4           47.0          237           +404.26%

benchmark               old allocs     new allocs     delta
BenchmarkFizzBuzz-4     5              5              +0.00%
BenchmarkIn-4           0              3              +Inf%

benchmark               old bytes     new bytes     delta
BenchmarkFizzBuzz-4     64            64            +0.00%
BenchmarkIn-4           0             72            +Inf%

```

**Comment by tcolgate** [comment]
This is because all arrays now get treated as possible clauses, so `{ "in": ["hello",["world","hello"]] }` uses a clause as the second argument, instead of using a "vanilla" array. This may be avoidable, but I need to have a think.

**Comment by tcolgate** [comment]
Ok, I've managed to avoid the allocation in the common case:
```benchmark               old ns/op     new ns/op     delta
BenchmarkFizzBuzz-4     531           539           +1.45%
BenchmarkIn-4           47.0          46.2          -1.60%

benchmark               old allocs     new allocs     delta
BenchmarkFizzBuzz-4     5              5              +0.00%
BenchmarkIn-4           0              0              +0.00%

benchmark               old bytes     new bytes     delta
BenchmarkFizzBuzz-4     64            64            +0.00%
BenchmarkIn-4           0             0             +0.00%
```

**Comment by tcolgate** [comment]
Thanks for the issue. This is the first one we've had on this repo, would you might me asking what you are using this for? It sounds like it might be quite interesting.

**Comment by stapelberg** [comment]
> Thanks for the issue. This is the first one we've had on this repo, would you might me asking what you are using this for? It sounds like it might be quite interesting.

Thanks for fixing this!

I’m trying to extend my covid certificate decoder/verifier (https://github.com/stapelberg/coronaqr) to also support covid certificate business rules (which country accepts what sort of vaccines, how long different test types are considered valid, etc.), which are implemented using certlogic, a subset of jsonlogic: https://github.com/ehn-dcc-development/dgc-business-rules/

I’ll try to clean up and push my pending commit soon now that the fix is in :)

**Comment by tcolgate** [comment]
Cheers
